name: CI Pipeline

on:
  push:
    branches:
      - wave


jobs:
  build-and-test:
    runs-on: ubuntu-latest





  send-notification:
    needs: merge-to-main
    runs-on: ubuntu-latest

    steps:
      - name: Send email notification
        uses: dawidd6/action-send-mail@v2
        with:
          server_address: smtp.example.com
          server_port: 587
          username: ${{ secrets.SMTP_USERNAME }}
          password: ${{ secrets.SMTP_PASSWORD }}
          subject: "CI Pipeline Status: ${{ job.status }}"
          body: |
            The CI pipeline status for branch wave is: ${{ job.status }}
            Please review the results.
        if: needs.merge-to-main.result == 'success'